spring:
  datasource:
    url: jdbc:postgresql://172.17.0.2:5432/itmed
    password: husanboy2002
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
server:
  port: 8082
